### PR TITLE
New action to support API v2

### PR DESCRIPTION
**Pull request by luiyen**
What's new:
- x-api-token header
- V2 API path
- V2 API parameters
- V2 response

### CODE REVIEW

**Review by ntnthien — APPROVED** [review]

**Comment by TSkovsgaard** [comment]
I believe we need this to merged now ?
Screenshot 2020-12-02 at 08 17 28

**Comment by michalcichon** [comment]
Hey, I just updated the original `lokalise.rb` as the old one doesn't work at all! I don't think it makes sense to keep it. I didn't change the input parameters, so it's simply update and forget change.

New pull request: https://github.com/lokalise/lokalise-fastlane-actions/pull/17

cc @ntnthien

**Comment by beinarovic** [comment]
Hey guys, I have merged PR [#17](https://github.com/lokalise/lokalise-fastlane-actions/pull/17), so we will take some time to look into this one.
Again, sorry for the delay, we are quite busy lately.

**Comment by ntnthien** [comment]
Sorry from my side from missing @michalcichon's comment too.

**Comment by luiyen** [comment]
Thanks, guys. 
Gonna close this MR.

**Pull request closed without merging**
