### PR TITLE
Fix no params

### PR DESCRIPTION
**Pull request by DmitryKotelevets**
Fixed "upload_metadata", "make_key_object_from_metadata" parameters

### CODE REVIEW

**Comment by BasouKazuma** [comment]
Verified that this fixes the method signature error introduced in this commit: https://github.com/lokalise/lokalise-fastlane-actions/commit/552bb2d93cb3df93bd4c0cc95ac2ce593e6e39fc

**Comment by codedbypm** [comment]
How come this PR takes so long to be merged?

**Comment by bnussbau** [comment]
bump! please merge this PR, because the lokalise_metadata fuction is broken

**Comment by BasouKazuma** [comment]
I'm in the process of transferring this to the Lokalise team but in the meantime I ported this repo to work as a Fastlane Plugin which you can use. I cleaned some things up there and changed some functionality so look at the README.
https://github.com/BasouKazuma/fastlane-plugin-lokalise

**Comment by bnussbau** [comment]
> I'm in the process of transferring this to the Lokalise team but in the meantime I ported this repo to work as a Fastlane Plugin which you can use. I cleaned some things up there and changed some functionality so look at the README.
> https://github.com/BasouKazuma/fastlane-plugin-lokalise

thank you!

**Pull request merged**
